version: "3"

services:
  scrapy:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./jobs_project:/jobs_project
    depends_on:
      - postgres
    ports:
      - "80:80"

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: canaria
    ports:
      - "54321:5432"
